name: Generate and Release CRD Docs and other release artifacts

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  setup:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      # the tag name (or empty string)
      tag: ${{ steps.tag.outputs.tag || '' }}
      # experimental tag derived from tag (or empty string)
      tag_experimental: ${{ steps.tag.outputs.tag && format('{0}-experimental', steps.tag.outputs.tag) || '' }}
    steps:
      - name: Checkout push/tag ref
        uses: actions/checkout@v5

      - id: tag
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  generate-release:
    needs: setup
    if: needs.setup.outputs.tag != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod' 

      - name: Install crd-ref-docs tool
        run: go install github.com/elastic/crd-ref-docs@latest

      - name: Generate CRD documentation
        run: |
          $HOME/go/bin/crd-ref-docs \
            --renderer=markdown \
            --source-path=./api \
            --config=./config/crd/crd-doc-config.yaml \
            --output-path=./config/crd/crd-docs.md

      - name: Generate Release module artifacts for tag release
        if: needs.setup.outputs.tag != ''
        run: |
          set -e
          make build-installer 
          cp ./dist/install.yaml registry-cache.yaml
        env:
          IMG: ${{ needs.setup.outputs.tag }}

      - name: Generate Release module artifacts for experimental tag release
        if: needs.setup.outputs.tag_experimental != ''
        run: | 
          set -e
          make build-installer
          cp ./dist/install.yaml registry-cache-experimental.yaml
        env:
          IMG: ${{ needs.setup.outputs.tag_experimental }}

      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v2
        with:
          files: | 
            ./config/crd/crd-docs.md
            ./registry-cache.yaml
            ./registry-cache-experimental.yaml
            ./config/samples/default-registry_cache_cr.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
